module.exports = [
  `int main() { return (1 + 1); };`, `2`,
  `int main() { return (-1 + 4); };`, `3`,
  `int main() { return (2 * 3); };`, `6`,
  `int main() { return (10 / 2); };`, `5`,
  `int main() { return (10 / 3); };`, `3`,
  `int main() { return (6 % 4); };`, `2`,
  `int main() { return (3 % 9); };`, `3`,
  `int main() { return (0 > -1); };`, `1`,
  `int main() { return (3 > 2); };`, `1`,
  `int main() { return (2 >= 1); };`, `1`,
  `int main() { return (2 > 3); };`, `0`,
  `int main() { return (1 < 2); };`, `1`,
  `int main() { return (4 <= 4); };`, `1`,
  `int main() { return (3 < 5); };`, `1`,
  `int main() { return (2 == 2); };`, `1`,
  `int main() { return (0 == 0); };`, `1`,
  `int main() { return (1 == 0); };`, `0`,
  `int main() { return (0 != 1); };`, `1`,
  `int main() { return (2 != 2); };`, `0`,
  `int main() { return (1 && 1); };`, `1`,
  `int main() { return (1 && 0); };`, `0`,
  `int main() { return (0 && 1); };`, `0`,
  `int main() { return (2 && 1); };`, `1`,
  `int main() { return (0 && 2); };`, `0`,
  `int main() { return (2 && 0); };`, `0`,
  `int main() { return (1 || 0); };`, `1`,
  `int main() { return (0 || 1); };`, `1`,
  `int main() { return (2 || 0); };`, `1`,
  `int main() { return (0 || 0); };`, `0`,
  `int main() { return (1 || 1); };`, `1`,
  `int main() { return (2 || 2); };`, `1`,
  `int main() { return ((1 == 0) || (2 > 3) || (1 != 0)); };`, `1`,
  `int main() { return (!0); };`, `1`,
  `int main() { return (!1); };`, `0`,
  `int main() { return (!(1 == 1)); };`, `0`,
  `int main() { return (!!(1)); };`, `1`,
  `int main() { return (1 == 2 || 1 != 0); };`, `1`,
  `int main() { return ((1 == 1) && (1 >= 1)); };`, `1`,
  `int main() { return ((1 != 1) && (1 >= 1)); };`, `0`,
  `int main() { return (1 | 2); };`, `3`,
  `int main() { return (2 | 5); };`, `7`,
  `int main() { return (2 | 7); };`, `7`,
  `int main() { return (1 & 2); };`, `0`,
  `int main() { return (2 & 5); };`, `0`,
  `int main() { return (2 & 7); };`, `2`,
  `int main() { return (2 & 5); };`, `0`,
  `int main() { return (~0); };`, `-1`,
  `int main() { return (~2); };`, `-3`,
  `int main() { return (~-1); };`, `0`,
  `int main() { return (2 ^ 6); };`, `4`,
  `int main() { return (15 ^ 5); };`, `10`,
  `int main() { return (2 << 8); };`, `512`,
  `int main() { return (3 << 4); };`, `48`,
  `int main() { return (8 >> 3); };`, `1`,
  `int main() { return (16 >> 2); };`, `4`,
  `int main() { return (0x52b2a7 == 5419687); };`, `1`
];
